services:
  - docker

before_install:
  - docker pull biothings/biothings-studio:0.2a
  - docker run --rm --name test_studio -p 8080:8080 -p 7080:7080 -p 8000:8000 -d biothings/biothings-studio
  - docker ps -a

script:
- echo ok
